# Nome da aplicação (usado como Issuer do Token)
spring.application.name=cine-the-golden-api

# Segredo do JWT (Em produção, use uma hash longa e segura)
api.security.token.secret=${JWT_SECRET:minha-senha-super-secreta-123}

# Configuração para mostrar o erro no console caso o token falhe
spring.web.error.include-exception=true
app.error.print-stacktrace=true


# Banco H2 (desenvolvimento)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Desativa o Flyway com H2 (ele é para PostgreSQL em produção)
spring.flyway.enabled=false

# H2 Console - Para você ver os dados pelo navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Cria as tabelas automaticamente baseado nas suas @Entity
# (No futuro, o Flyway cuidará disso, mas para o primeiro teste use 'update')
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
